Add DLQ URL & ARN to outputs
getlift/lift pull request #64
Opened 2021-06-30 16:47 UTC by M1ke

Resolves https://github.com/getlift/lift/issues/63

This may be a naive addition because I can see that the format of the references for `this.queue` is different and possibly it's not as easy to replicate. But it's a start

2021-06-30 17:16 UTC, t-richard requested changes
Thanks for starting this.

Not sure if this is needed and wanted in Lift to be honest. But maybe if you need it, some others will too.

So here are some comments on the implementation.

2021-06-30 17:16 UTC, t-richard commented on src/constructs/Queue.ts
> +            dlqArn: thus.getDlqArn(),
you can't use those functions as they use the Cloudformation stack outputs. But you need the references (Cloudformation's `Ref` or `GetAtt`) to be able to reference it custom cloudformation, function environment variables, event triggers on function etc

That's the purpose of `AwsProvider::getCloudFormationReference`. This function will use the CDK to resolve references which in the end uses CDK Tokens IIRC. 

Check `referenceQueueUrl` to get an idea of how to do it here.

2021-06-30 17:16 UTC, t-richard commented on src/constructs/Queue.ts
> +            dlqArn: thus.getDlqArn(),
and there is a type too. `thus` instead of `this`

2021-06-30 17:16 UTC, t-richard commented on src/constructs/Queue.ts
> +    async getDlqArn(): Promise<string | undefined> {
I think this is not needed regarding my previous comment.

2021-07-08 09:58 UTC, mnapoli commented
Following the discussion in https://github.com/M1ke/serverless-payments/pull/8 I don't think we should merge this.

I'll close this for now, we can always reopen later!

Thanks for the time spent on this!

2021-07-08 09:58 UTC, closed without merging